title: Axistroid
description: >- # this means to ignore newlines until "baseurl:"
  Notes on software engineering
baseurl: ""
url: ""
twitter_username: axistroid

# Build settings
theme: minima
plugins:
  - jekyll-feed

google_analytics: UA-167492313-1
show_excerpts: true
